---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cozyflow-necsus-dev
  namespace: envoy-gateway-system
spec:
  secretName: cozyflow-necsus-dev-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  commonName: cozyflow.necsus.dev
  dnsNames:
    - cozyflow.necsus.dev
    - cfapi.necsus.dev
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: cozyflow-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: envoy
  listeners:
    - name: cozyflow-https
      hostname: cozyflow.necsus.dev
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: cozyflow-necsus-dev-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
    - name: api-cozyflow-https
      hostname: cfapi.necsus.dev
      port: 443
      protocol: HTTPS
      tls:
        mode: Terminate
        certificateRefs:
          - name: cozyflow-necsus-dev-tls
            kind: Secret
      allowedRoutes:
        namespaces:
          from: All
